// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: execute_command.proto
#ifndef GRPC_execute_5fcommand_2eproto__INCLUDED
#define GRPC_execute_5fcommand_2eproto__INCLUDED

#include "execute_command.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ec {

class ExecuteCommand final {
 public:
  static constexpr char const* service_full_name() {
    return "ec.ExecuteCommand";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status sendReq(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::ec::CommandResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ec::CommandResp>> AsyncsendReq(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ec::CommandResp>>(AsyncsendReqRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ec::CommandResp>> PrepareAsyncsendReq(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ec::CommandResp>>(PrepareAsyncsendReqRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void sendReq(::grpc::ClientContext* context, const ::ec::CommandReq* request, ::ec::CommandResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void sendReq(::grpc::ClientContext* context, const ::ec::CommandReq* request, ::ec::CommandResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ec::CommandResp>* AsyncsendReqRaw(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ec::CommandResp>* PrepareAsyncsendReqRaw(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status sendReq(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::ec::CommandResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ec::CommandResp>> AsyncsendReq(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ec::CommandResp>>(AsyncsendReqRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ec::CommandResp>> PrepareAsyncsendReq(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ec::CommandResp>>(PrepareAsyncsendReqRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void sendReq(::grpc::ClientContext* context, const ::ec::CommandReq* request, ::ec::CommandResp* response, std::function<void(::grpc::Status)>) override;
      void sendReq(::grpc::ClientContext* context, const ::ec::CommandReq* request, ::ec::CommandResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ec::CommandResp>* AsyncsendReqRaw(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ec::CommandResp>* PrepareAsyncsendReqRaw(::grpc::ClientContext* context, const ::ec::CommandReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_sendReq_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status sendReq(::grpc::ServerContext* context, const ::ec::CommandReq* request, ::ec::CommandResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_sendReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_sendReq() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_sendReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendReq(::grpc::ServerContext* /*context*/, const ::ec::CommandReq* /*request*/, ::ec::CommandResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendReq(::grpc::ServerContext* context, ::ec::CommandReq* request, ::grpc::ServerAsyncResponseWriter< ::ec::CommandResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_sendReq<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_sendReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_sendReq() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ec::CommandReq, ::ec::CommandResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ec::CommandReq* request, ::ec::CommandResp* response) { return this->sendReq(context, request, response); }));}
    void SetMessageAllocatorFor_sendReq(
        ::grpc::MessageAllocator< ::ec::CommandReq, ::ec::CommandResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ec::CommandReq, ::ec::CommandResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_sendReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendReq(::grpc::ServerContext* /*context*/, const ::ec::CommandReq* /*request*/, ::ec::CommandResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* sendReq(
      ::grpc::CallbackServerContext* /*context*/, const ::ec::CommandReq* /*request*/, ::ec::CommandResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_sendReq<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_sendReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_sendReq() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_sendReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendReq(::grpc::ServerContext* /*context*/, const ::ec::CommandReq* /*request*/, ::ec::CommandResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_sendReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_sendReq() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_sendReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendReq(::grpc::ServerContext* /*context*/, const ::ec::CommandReq* /*request*/, ::ec::CommandResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendReq(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_sendReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_sendReq() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->sendReq(context, request, response); }));
    }
    ~WithRawCallbackMethod_sendReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendReq(::grpc::ServerContext* /*context*/, const ::ec::CommandReq* /*request*/, ::ec::CommandResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* sendReq(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_sendReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_sendReq() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ec::CommandReq, ::ec::CommandResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ec::CommandReq, ::ec::CommandResp>* streamer) {
                       return this->StreamedsendReq(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_sendReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sendReq(::grpc::ServerContext* /*context*/, const ::ec::CommandReq* /*request*/, ::ec::CommandResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsendReq(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ec::CommandReq,::ec::CommandResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_sendReq<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_sendReq<Service > StreamedService;
};

}  // namespace ec


#endif  // GRPC_execute_5fcommand_2eproto__INCLUDED
